# Generated by Django 3.1.7 on 2021-03-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('discription', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
